name: PlatformIO CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Cache PlatformIO
        uses: actions/cache@v3
        with:
          path: ~/.platformio
          key: ${{ runner.os }}-platformio-${{ hashFiles('**/platformio.ini') }}
          restore-keys: |
            ${{ runner.os }}-platformio-

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install PlatformIO
        run: |
          python -m pip install --upgrade pip
          pip install platformio

      - name: Build
        run: pio run

      - name: Add Build Status Badge
        continue-on-error: true
        uses: schneegans/dynamic-badges-action@v1.7.0
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: 46292c13ab8c70e68aa9619cad1d9560
          filename: esp32-homekit-SmartRoom-build.json
          label: "Build Status"
          message: ${{ job.status }}
          color: ${{ job.status == 'success' && 'success' || 'critical' }}
          namedLogo: github-actions

      - name: Check OTA Size
        id: ota_check
        continue-on-error: true
        run: |
          # Retrieve the partition file from platformio.ini
          PARTITION_FILE=$(grep "board_build.partitions" platformio.ini | cut -d '=' -f2 | tr -d ' ')
          if [ ! -f "$PARTITION_FILE" ]; then
            echo "Error: Partition file $PARTITION_FILE not found"
            echo "OTA_STATUS=Build failed - missing partition file" >> $GITHUB_ENV
            echo "check_failed=true" >> $GITHUB_ENV
            exit 1
          fi

          # Extract the line corresponding to the firmware partition (commonly "factory")
          FACTORY_PARTITION=$(awk -F, '$1 ~ /factory/ {print $0}' "$PARTITION_FILE")
          if [ -z "$FACTORY_PARTITION" ]; then
            echo "Error: Factory partition not found in $PARTITION_FILE"
            echo "OTA_STATUS=Build failed - no firmware partition" >> $GITHUB_ENV
            echo "check_failed=true" >> $GITHUB_ENV
            exit 1
          fi

          # Assume the size is in the 5th column; trim whitespace and check if it's hex
          MAX_OTA_SIZE=$(echo "$FACTORY_PARTITION" | awk -F, '{gsub(/^[ \t]+|[ \t]+$/, "", $5); print $5}')
          if [[ $MAX_OTA_SIZE == 0x* ]]; then
              MAX_OTA_SIZE=$(printf "%d" "$MAX_OTA_SIZE")
          fi

          echo "Maximum OTA size determined from partition file: $MAX_OTA_SIZE bytes"

          FIRMWARE_PATH=".pio/build/esp32doit-devkit-v1/firmware.bin"
          if [ ! -f "$FIRMWARE_PATH" ]; then
            echo "Error: Firmware file not found at $FIRMWARE_PATH"
            echo "OTA_STATUS=Build failed - no firmware" >> $GITHUB_ENV
            echo "check_failed=true" >> $GITHUB_ENV
            exit 1
          fi

          BINARY_SIZE=$(stat -c%s "$FIRMWARE_PATH")
          echo "Binary size: $BINARY_SIZE bytes"
          echo "Maximum OTA size: $MAX_OTA_SIZE bytes"

          if [ "$BINARY_SIZE" -gt "$MAX_OTA_SIZE" ]; then
            echo "OTA_STATUS=exceeded ($BINARY_SIZE bytes)" >> $GITHUB_ENV
            echo "check_failed=true" >> $GITHUB_ENV
            exit 1
          else
            PERCENT_USED=$((BINARY_SIZE * 100 / MAX_OTA_SIZE))
            echo "OTA_STATUS=ready ($PERCENT_USED% used)" >> $GITHUB_ENV
            echo "check_failed=false" >> $GITHUB_ENV
          fi

      - name: Add OTA Status Badge
        if: always()
        continue-on-error: true
        uses: schneegans/dynamic-badges-action@v1.7.0
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: 46292c13ab8c70e68aa9619cad1d9560
          filename: esp32-homekit-ota.json
          label: "OTA Status"
          message: ${{ env.OTA_STATUS || 'Failed to check size' }}
          color: >-
            ${{ 
              env.check_failed == 'true' && 'critical' ||
              env.OTA_STATUS != '' && 'success' ||
              'critical'
            }}
          namedLogo: github-actions
