name: PlatformIO CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Cache PlatformIO
        uses: actions/cache@v3
        with:
          path: ~/.platformio
          key: ${{ runner.os }}-platformio-${{ hashFiles('**/platformio.ini') }}
          restore-keys: |
            ${{ runner.os }}-platformio-

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install PlatformIO
        run: |
          python -m pip install --upgrade pip
          pip install platformio

      - name: Build
        run: pio run

      - name: Add Build Status Badge
        continue-on-error: true
        uses: schneegans/dynamic-badges-action@v1.7.0
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: 46292c13ab8c70e68aa9619cad1d9560
          filename: esp32-homekit-SmartRoom-build.json
          label: "Build Status"
          message: ${{ job.status }}
          color: ${{ job.status == 'success' && 'success' || 'critical' }}
          namedLogo: github-actions

      - name: Check OTA Size
        id: ota_check
        continue-on-error: true
        run: |
          # Default max OTA size in bytes (1.25 MB)
          DEFAULT_MAX_OTA_SIZE=1310720

          # Try to grab the partition information from platformio.ini
          PARTITION_LINE=$(grep "board_build.partitions" platformio.ini || true)
          if [ -z "$PARTITION_LINE" ]; then
              echo "No board_build.partitions found in platformio.ini, using default max OTA size of 1.25MB."
              MAX_OTA_SIZE=$DEFAULT_MAX_OTA_SIZE
          else
              PARTITION_FILENAME=$(echo "$PARTITION_LINE" | cut -d '=' -f2 | tr -d ' ')
              echo "Partition filename from platformio.ini: $PARTITION_FILENAME"

              # Attempt to locate the partition file locally
              PARTITION_FILE=$(find . -type f -name "$PARTITION_FILENAME" | head -n 1)
              if [ -z "$PARTITION_FILE" ]; then
                  echo "Partition file $PARTITION_FILENAME not found locally. Downloading it..."
                  curl -o "$PARTITION_FILENAME" https://raw.githubusercontent.com/espressif/arduino-esp32/master/tools/partitions/$PARTITION_FILENAME
                  if [ ! -f "$PARTITION_FILENAME" ]; then
                      echo "Warning: Unable to download the partition file $PARTITION_FILENAME. Using default max OTA size of 1.25MB."
                      MAX_OTA_SIZE=$DEFAULT_MAX_OTA_SIZE
                  else
                      PARTITION_FILE="$PARTITION_FILENAME"
                      echo "Downloaded partition file and saved as $PARTITION_FILE"
                  fi
              fi

              # If a partition file is available, try to parse it to find the factory partition.
              if [ -n "$PARTITION_FILE" ]; then
                  FACTORY_PARTITION=$(awk -F, '$1 ~ /factory/ {print $0}' "$PARTITION_FILE")
                  if [ -z "$FACTORY_PARTITION" ]; then
                      echo "Warning: Factory partition not found in $PARTITION_FILE. Using default max OTA size of 1.25MB."
                      MAX_OTA_SIZE=$DEFAULT_MAX_OTA_SIZE
                  else
                      MAX_OTA_SIZE=$(echo "$FACTORY_PARTITION" | awk -F, '{gsub(/^[ \t]+|[ \t]+$/, "", $5); print $5}')
                      if [[ $MAX_OTA_SIZE == 0x* ]]; then
                          MAX_OTA_SIZE=$(printf "%d" "$MAX_OTA_SIZE")
                      fi
                  fi
              else
                  echo "No partition file found; using default max OTA size of 1.25MB."
                  MAX_OTA_SIZE=$DEFAULT_MAX_OTA_SIZE
              fi
          fi

          echo "Maximum OTA size: $MAX_OTA_SIZE bytes"

          # Locate and check the firmware binary
          FIRMWARE_PATH=".pio/build/esp32doit-devkit-v1/firmware.bin"
          if [ ! -f "$FIRMWARE_PATH" ]; then
              echo "Error: Firmware file not found at $FIRMWARE_PATH"
              echo "OTA_STATUS=Build failed - no firmware" >> $GITHUB_ENV
              echo "check_failed=true" >> $GITHUB_ENV
              exit 1
          fi

          BINARY_SIZE=$(stat -c%s "$FIRMWARE_PATH")
          echo "Binary size: $BINARY_SIZE bytes"

          if [ "$BINARY_SIZE" -gt "$MAX_OTA_SIZE" ]; then
              echo "OTA_STATUS=exceeded ($BINARY_SIZE bytes)" >> $GITHUB_ENV
              echo "check_failed=true" >> $GITHUB_ENV
              exit 1
          else
              PERCENT_USED=$((BINARY_SIZE * 100 / MAX_OTA_SIZE))
              echo "OTA_STATUS=ready ($PERCENT_USED% used)" >> $GITHUB_ENV
              echo "check_failed=false" >> $GITHUB_ENV
          fi

      - name: Add OTA Status Badge
        if: always()
        continue-on-error: true
        uses: schneegans/dynamic-badges-action@v1.7.0
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: 46292c13ab8c70e68aa9619cad1d9560
          filename: esp32-homekit-ota.json
          label: "OTA Status"
          message: ${{ env.OTA_STATUS || 'Failed to check size' }}
          color: >-
            ${{ 
              env.check_failed == 'true' && 'critical' ||
              env.OTA_STATUS != '' && 'success' ||
              'critical'
            }}
          namedLogo: github-actions
